apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: yichu21/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: yichu21/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
